### ISSUE TITLE
Ability to reject all?

### ISSUE THREAD

**Issue by Anahkiasen** [statikbe/laravel-cookie-consent#22]
In a few GDPR countries [you have to provide a button](https://www.iubenda.com/en/help/23748-reject-button-cookie-banner) to Reject All in addition to Accept all, I wanted to customize this myself but I'm not sure it's possible without touching the code itself, could this be a possible feature to be added?

**Comment by kristofser** [comment]
hi @Anahkiasen 

This is a feature that will be added soon. (somewhere between the next 2 months) :)

**Comment by Anahkiasen** [comment]
Perfect, thanks!

**Comment by kristofser** [comment]
Dear @Anahkiasen We've changed the way our cookie module works in a different way.
Since Rejecting all is most of the time not possible We did the following:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/5928907/160388931-09d92cfb-2c66-497d-a845-6c9ab662ad9e.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/5928907/160389052-033e0df2-7e04-48b1-ad4b-765efca96890.png">



This is now available in the latest update
